version: "3.9"
services:

  authreally:
    build:
      context: ./AuthReally
    ports:
      - "4433:443"
    volumes:
      - authreallyCerts:/app/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

  middling:
    build:
      context: ./Middling
      args:
        SERVICE_NAME: "Middling"
        USERNAME: "arthur"
    depends_on:
      - authreally
    ports:
      - "4434:443"
    volumes:
      - middlingCerts:/app/certs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
          pids: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

volumes:
    authreallyCerts:
        external: true
    middlingCerts:
        external: true
